// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHjGOfxPU0zTGzDO5isjhIsSig8aOgGvc',
    appId: '1:857612616011:web:c30facf034bc7caeb568ce',
    messagingSenderId: '857612616011',
    projectId: 'suicide-prevention-826a9',
    authDomain: 'suicide-prevention-826a9.firebaseapp.com',
    storageBucket: 'suicide-prevention-826a9.appspot.com',
    measurementId: 'G-FS2DHTK262',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhIsirC4KLjrlediExE3MxFNfoWvqgn5s',
    appId: '1:857612616011:android:179edf2da2066556b568ce',
    messagingSenderId: '857612616011',
    projectId: 'suicide-prevention-826a9',
    storageBucket: 'suicide-prevention-826a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARsvjdB3D2FLxmHBNCesLkV3r6i-7PHrQ',
    appId: '1:857612616011:ios:713b59bdf1bd9ad2b568ce',
    messagingSenderId: '857612616011',
    projectId: 'suicide-prevention-826a9',
    storageBucket: 'suicide-prevention-826a9.appspot.com',
    androidClientId: '857612616011-48k9ii6v4h9pkpih6kp3egi6euu30mjm.apps.googleusercontent.com',
    iosClientId: '857612616011-p1i7gfqaahh516bn3749hljrlop11re5.apps.googleusercontent.com',
    iosBundleId: 'com.example.sucidePrevention',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARsvjdB3D2FLxmHBNCesLkV3r6i-7PHrQ',
    appId: '1:857612616011:ios:713b59bdf1bd9ad2b568ce',
    messagingSenderId: '857612616011',
    projectId: 'suicide-prevention-826a9',
    storageBucket: 'suicide-prevention-826a9.appspot.com',
    androidClientId: '857612616011-48k9ii6v4h9pkpih6kp3egi6euu30mjm.apps.googleusercontent.com',
    iosClientId: '857612616011-p1i7gfqaahh516bn3749hljrlop11re5.apps.googleusercontent.com',
    iosBundleId: 'com.example.sucidePrevention',
  );
}
